const routes = {
  home: '/',
  about: '/about',
  contact: '/contact',
  ourStore: '/product',
  ourStoreSearch: '/product/:slug',
  singleProduct: '/product/:id',
  blogs: '/blogs',
  singleBlog: '/blog/:id',
  compareProduct: '/compare-product',
  wishlist: '/wishlist',
  cart: '/cart',
  checkOut: '/check-out',
  information: '/information',
  orders: '/orders',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password/:token',
  privacyPolicy: '/privacy-policy',
  refundPolicy: '/refund-policy',
  shippingPolicy: '/shipping-policy',
  termAndConditions: '/term-conditions',
}

export default routes
